CREATE TABLE [dbo].[test] (
    [Id]                    INT             IDENTITY (1, 1) NOT NULL,
    [OptionDataId]          INT             NULL,
    [StrikePrice]           DECIMAL (18, 2) NULL,
    [OptionType]            VARCHAR (10)    NULL,
    [SignalType]            VARCHAR (50)    NULL,
    [SignalScore]           DECIMAL (8, 4)  NULL,
    [LastPrice]             DECIMAL (18, 6) NULL,
    [PrevLastPrice]         DECIMAL (18, 6) NULL,
    [PricePctChange]        DECIMAL (9, 4)  NULL,
    [OI]                    DECIMAL (18)    NULL,
    [PrevOI]                DECIMAL (18)    NULL,
    [OIPctChange]           DECIMAL (9, 4)  NULL,
    [Volume]                BIGINT          NULL,
    [PrevVolume]            BIGINT          NULL,
    [VolumePctChange]       DECIMAL (9, 4)  NULL,
    [ImpliedVolatility]     DECIMAL (9, 6)  NULL,
    [PrevImpliedVolatility] DECIMAL (9, 6)  NULL,
    [IVPctChange]           DECIMAL (9, 4)  NULL,
    [Delta]                 DECIMAL (9, 6)  NULL,
    [Gamma]                 DECIMAL (9, 6)  NULL,
    [Vega]                  DECIMAL (9, 6)  NULL,
    [CreatedAt]             DATETIME2 (7)   NULL,
    [GeneratedAt]           DATETIME2 (7)   NULL,
    [Diff]                  INT             NULL,
    [ExpiryDate]            DATE            NULL,
    [Result]                VARCHAR (500)   NULL
);

